# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aisync < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    url "https://github.com/sushichan044/aisync/releases/download/v0.1.1/aisync_Darwin_all.tar.gz"
    sha256 "a9abe8aa3ed0ad9dcf33530bfaf1614b0b7b97f72422f452cfacef70bd124486"

    def install
      bin.install "aisync"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/aisync/releases/download/v0.1.1/aisync_Linux_x86_64.tar.gz"
      sha256 "a831dbc08c5418fdb75ca99bc7796773ac39f08f26e33612f9ae9f477046bdb8"
      def install
        bin.install "aisync"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/aisync/releases/download/v0.1.1/aisync_Linux_arm64.tar.gz"
      sha256 "e3c3ef20c540b2378b563aa8df06f6e921f575d4348cd719210c93d5dc3b5676"
      def install
        bin.install "aisync"
      end
    end
  end
end
