# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aisync < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    url "https://github.com/sushichan044/aisync/releases/download/v0.1.0/aisync_Darwin_all.tar.gz"
    sha256 "0205a699d6bf2b3d31f04b0a012d29b45775b86b737ee2afab43dae7ad86bb17"

    def install
      bin.install "aisync"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/aisync/releases/download/v0.1.0/aisync_Linux_x86_64.tar.gz"
      sha256 "ee47a8dd3af92100495d3a04856194788504f76e9edd6196647e938a89a0d8af"
      def install
        bin.install "aisync"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/aisync/releases/download/v0.1.0/aisync_Linux_arm64.tar.gz"
      sha256 "0ee20bd11abe3c75a7ee584486dcc60dcfdff6157949ee3325f176339e10e7d8"
      def install
        bin.install "aisync"
      end
    end
  end
end
