# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ajisai < Formula
  desc ""
  homepage ""
  version "0.4.4"

  on_macos do
    url "https://github.com/sushichan044/ajisai/releases/download/v0.4.4/ajisai_Darwin_all.tar.gz"
    sha256 "8c5c0f24dd2ad8fa3fc8f9060a67d1a2e78e7579b6414edb874141586a3cfc3b"

    def install
      bin.install "ajisai"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/ajisai/releases/download/v0.4.4/ajisai_Linux_x86_64.tar.gz"
      sha256 "605826b4c9c87edfb76f7b8652072779b23d8f68bf2e24939ac5b3c39aae488a"
      def install
        bin.install "ajisai"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/ajisai/releases/download/v0.4.4/ajisai_Linux_arm64.tar.gz"
      sha256 "680885e904fcb76d1b49baaa554989fc358d40e15e20f058b83a36fa1ebfdd58"
      def install
        bin.install "ajisai"
      end
    end
  end
end
