# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ajisai < Formula
  desc ""
  homepage ""
  version "0.5.3"

  on_macos do
    url "https://github.com/sushichan044/ajisai/releases/download/v0.5.3/ajisai_Darwin_all.tar.gz"
    sha256 "bdc475d272fa25e0f3328a675ec8268e7822a10fc8a0f9cf59150ede6a4e5b67"

    def install
      bin.install "ajisai"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/ajisai/releases/download/v0.5.3/ajisai_Linux_x86_64.tar.gz"
      sha256 "7161ef665da71ad3f4da70a0bd4641695e5567660317d0d0e5ca353207068f0a"
      def install
        bin.install "ajisai"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sushichan044/ajisai/releases/download/v0.5.3/ajisai_Linux_arm64.tar.gz"
      sha256 "13c8687caaae97b26337338c1affa3bfb687687e2fef79ac74f4d97e627590d9"
      def install
        bin.install "ajisai"
      end
    end
  end
end
