# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdfm" do
  desc "Glob markdown files and get each frontmatters."
  homepage "https://github.com/sushichan044/mdfm"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdfm"

  on_macos do
    url "https://github.com/sushichan044/mdfm/releases/download/v0.1.2/mdfm_Darwin_all.tar.gz"
    sha256 "9e2a3e95e3e66130ca9a0e6afc4a3549abf752457ec1550c96e4fd25c6783b0c"
  end

  on_linux do
    on_intel do
      url "https://github.com/sushichan044/mdfm/releases/download/v0.1.2/mdfm_Linux_x86_64.tar.gz"
      sha256 "2bdac5e5e7221dd20710e1edbc3158b76093c5d0abbf53bacc148815f02bb701"
    end
    on_arm do
      url "https://github.com/sushichan044/mdfm/releases/download/v0.1.2/mdfm_Linux_arm64.tar.gz"
      sha256 "2b6b55a3cc853dbfd48d3e9e6a9d8c9f73a84ccffb94c550f8aa958ae5621e46"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdfm"]
    end
  end

  # No zap stanza required
end
