# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdfm" do
  desc "Glob markdown files and get each frontmatters."
  homepage "https://github.com/sushichan044/mdfm"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdfm"

  on_macos do
    url "https://github.com/sushichan044/mdfm/releases/download/v0.1.0/mdfm_Darwin_all.tar.gz"
    sha256 "0ac3181df852c39eae4bfacc5d867b8a45b6ee0d6a1196a77730c9b52e137bbc"
  end

  on_linux do
    on_intel do
      url "https://github.com/sushichan044/mdfm/releases/download/v0.1.0/mdfm_Linux_x86_64.tar.gz"
      sha256 "7cb414ca07a2eedd87246588e807d7fd8be273decdc675cd0ed79a5de54018c6"
    end
    on_arm do
      url "https://github.com/sushichan044/mdfm/releases/download/v0.1.0/mdfm_Linux_arm64.tar.gz"
      sha256 "630caa58e40b0adbcf16fc275193884189ecd39626410ee6974559c689e6e948"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdfm"]
    end
  end

  # No zap stanza required
end
