# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdfm" do
  name "mdfm"
  desc "Glob markdown files and get each frontmatters."
  homepage "https://github.com/sushichan044/mdfm"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdfm"

  on_macos do
    url "https://github.com/sushichan044/mdfm/releases/download/v#{version}/mdfm_Darwin_all.tar.gz"
    sha256 "7d0bf8011f771811a95f325b939d7f7022a30fb266f3936c35fb8640ca8ff314"
  end

  on_linux do
    on_intel do
      url "https://github.com/sushichan044/mdfm/releases/download/v#{version}/mdfm_Linux_x86_64.tar.gz"
      sha256 "d5cb9e15fcce16f3af97f3143a0ce4062433ccfb6a287919ddf9705699151a87"
    end
    on_arm do
      url "https://github.com/sushichan044/mdfm/releases/download/v#{version}/mdfm_Linux_arm64.tar.gz"
      sha256 "fe30eb39bc9aaf7f9980549a87d333a3963d0a00419ea0a7e2a70094b909c883"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdfm"]
    end
  end

  # No zap stanza required
end
