# This file was generated by GoReleaser. DO NOT EDIT.
cask "sidetable" do
  name "sidetable"
  desc "A tool that helps manage a project-local private area."
  homepage "https://github.com/sushichan044/sidetable"
  version "2.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sidetable"
  bash_completion "completions/sidetable.bash"
  zsh_completion "completions/sidetable.zsh"
  fish_completion "completions/sidetable.fish"

  on_macos do
    on_intel do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Darwin_x86_64.tar.gz"
      sha256 "a65815b0e35b530f04677a9cbb8f577091505b98d220556d61858ea75b33d0a0"
    end
    on_arm do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Darwin_arm64.tar.gz"
      sha256 "fd951aec00e6da05dc9fc520437d74a76ccd52803b2755820a1a110a3eafd498"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Linux_x86_64.tar.gz"
      sha256 "783cb8cab89ea992e013ec25e889c2bc95de95aea897e5b312a8523130cd566c"
    end
    on_arm do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Linux_arm64.tar.gz"
      sha256 "47a3730281419ae2e253e875ff5cbbb69811f2703d4a98b469adde258e26c1f6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sidetable"]
    end
  end

  # No zap stanza required
end
