# This file was generated by GoReleaser. DO NOT EDIT.
cask "sidetable" do
  name "sidetable"
  desc "A tool that helps manage a project-local private area."
  homepage "https://github.com/sushichan044/sidetable"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sidetable"
  bash_completion "completions/sidetable.bash"
  zsh_completion "completions/sidetable.zsh"
  fish_completion "completions/sidetable.fish"

  on_macos do
    on_intel do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Darwin_x86_64.tar.gz"
      sha256 "76996560ea10ca61738c050992d0570d0b50366827439857d2095ff1088323c3"
    end
    on_arm do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Darwin_arm64.tar.gz"
      sha256 "2d43d709e9e200543efbc0373ba21a3031805e7f3637eb5057ff275fac1a1cce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Linux_x86_64.tar.gz"
      sha256 "e477374a38d1d5030fcdc8c9ca874ac19a96a9c2e73f1768e2048e48b4e8259d"
    end
    on_arm do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Linux_arm64.tar.gz"
      sha256 "8da526348c81765919448cd98ae51ea8ddd2f717303491b103690726f8bfe6fc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sidetable"]
    end
  end

  # No zap stanza required
end
