# This file was generated by GoReleaser. DO NOT EDIT.
cask "sidetable" do
  name "sidetable"
  desc "A tool that helps manage a project-local private area."
  homepage "https://github.com/sushichan044/sidetable"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sidetable"
  bash_completion "completions/sidetable.bash"
  zsh_completion "completions/sidetable.zsh"
  fish_completion "completions/sidetable.fish"

  on_macos do
    on_intel do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Darwin_x86_64.tar.gz"
      sha256 "a772782139458875b2c941832757a0a2bbf5be6942d57b54679b172afb3116bc"
    end
    on_arm do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Darwin_arm64.tar.gz"
      sha256 "4635718382bb58a07a03499ebf267feb54f27062e1cec578aab4859efea5d6c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Linux_x86_64.tar.gz"
      sha256 "25ffded0d81a64442b5494a1ea5b091af46f0764f5ca0212bc17334a6dc635b9"
    end
    on_arm do
      url "https://github.com/sushichan044/sidetable/releases/download/v#{version}/sidetable_Linux_arm64.tar.gz"
      sha256 "7c27521a6d77eefb11855983d7e34e27cc282e0eb8c96cc6b5a27cbbb467edd0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sidetable"]
    end
  end

  # No zap stanza required
end
